### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/iva.milosevic#1]
Hi @ivamil,

Please do the following:
1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by ivamil** [comment]
Hi @valentinacupac ,

 I've got test ticket.

Kind regards,
Iva

**Comment by valentinajemuovic** [comment]
Thanks @ivamil, please close the ticket now.

**Comment by valentinajemuovic** [comment]
@ivamil, please check this ticket, it needs to be closed....
