### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by ivamil** [alptium/iva.milosevic#4]

**Comment by valentinajemuovic** [comment]
@ivamil:
1. See point 2 here https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World
2. See my code for formatting of brackets { } associatged with if statements
3. There is a missing "try" block around the scanner, see my code sample.
4. See point 28 here https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World

**Comment by valentinajemuovic** [comment]
@ivamil, still formatting issues, so we'll review this during a meeting.

**Comment by valentinajemuovic** [comment]
@ivamil, please fix based on our meeting.

**Comment by valentinajemuovic** [comment]
@ivamil, good, except there was an improvement, which I pushed now - putting variable declaration and initialization in one possible, where possible (since now need to do it over 2 lines).

Closing ticket.
